### ISSUE TITLE
Strange error on some machine

### ISSUE THREAD

**Issue by attacc** [yambo-code/yambopy#49]
Dear all 
I get this error on the last version of YamboPy

  from yambopy import *
  File "/home/attacc/SOFTWARE/yambopy/yambopy/__init__.py", line 108, in <module>
    from yambopy.letzelphc_interface.lelph2y import *
  File "/home/attacc/SOFTWARE/yambopy/yambopy/letzelphc_interface/lelph2y.py", line 53
    match code:
          ^
SyntaxError: invalid syntax

I don't know it is a problem of my machine or other things, I just would like to know if someone else get the same, and if you have a simple solution
best 
Claudio

**Comment by attacc** [comment]
I solved this error.
YamboPy was installed in development mode in some machine with an old python, so the system
does not check that the last version after a "git pull" is not compatible anymore with that python.
Ciao cioa

**Comment by palful** [comment]
Ciao Claudio,

Yes it was a version problem. The `match` statement only works from python 3.10 onwards. This is also probably sloppy coding by me because in that class (which is the latest part of the code) I decided to use this statement which breaks the compatibility with python 3.8. It is the only instance where the new `match` statement appears.

If one does not want to change the python version, it is sufficient to change `match` into an `if-else` statement as:

```
if code == 'lelphc':
    self.get_elph_variables_LELPHC(OBJ)
else:
    raise NotImplementedError("Code %s not found or implemented" % code)
```
